### ISSUE TITLE
Adapter has too many deps

### ISSUE THREAD

**Issue by jetersen** [probot/adapter-github-actions#20]
Seems the adapter is having too many deps, nock should definitely be a dev dependency.
https://github.com/probot/adapter-github-actions/blob/34665d741b53510af74aa065efb3fb459c2263c1/package.json#L31-L35

**Comment by gr2m** [comment]
Oopsies! It should indeed, yes. The others are correct though, they are all used for logging in https://github.com/probot/adapter-github-actions/blob/34665d741b53510af74aa065efb3fb459c2263c1/pino-transport-github-actions.js

Can you send a pull request to move `nock` to `devDependencies`?

**Comment by jetersen** [comment]
created #21
