### ISSUE TITLE
cron based actions

### ISSUE THREAD

**Issue by jbjonesjr** [probot/adapter-github-actions#23]
looking to replace specifically a `scheduled-probot` with a cron based action. it's clearly not throwing the schedule.repository event when a cron happens, @gr2m have you looked or explored what that integration path looks like?

**Comment by gr2m** [comment]
use the `schedule` trigger for the workflow and then in your

```js
app.on("schedule", (context) => { ... })
```

That should work?

**Comment by jbjonesjr** [comment]
That'll do it!

**Comment by jbjonesjr** [comment]
lightweight event payload though....

```
 event: {
    id: '597502923',
    name: 'schedule',
    payload: { schedule: '*/5 * * * *' }
  },
```

is that from the actions side I assume? I didn't find reference to the `schedule` event in the adapter code anywhere. I assume that means most of the normal helper functions and octokit object won't work. 

I kind of want to catch the schedule event, augment it with workflow variables, and then process it properly. Is that crazy? What am I missing....

**Comment by jbjonesjr** [comment]
okay, i got all this working. I'll explore in a PR what could be done to make migrating a probot app to an action easier
